### ISSUE TITLE
Headerの検索をcase-insensitiveにする

### ISSUE THREAD

**Issue by Hurumy** [Hurumy/webserv#112]
します
- 元データに手を入れないようにしつつ、計算量も増やしすぎない
→Headerクラスを実装し、std::mapにCompareをわたす案が最有力

**Comment by ShotaTanemura** [comment]
> します
> 
> * 元データに手を入れないようにしつつ、計算量も増やしすぎない
>   →Headerクラスを実装し、std::mapにCompareをわたす案が最有力

@Hurumy 
`Header` クラスを実装する必要はないと思います。
