### ISSUE TITLE
CGIではいたレスポンスの中に改行が入っている時がある？

### ISSUE THREAD

**Issue by Hurumy** [Hurumy/webserv#121]
？？
<img width="918" alt="スクリーンショット 2023-11-14 17 32 36" src="https://github.com/Hurumy/webserv/assets/61591984/89fc53cb-70d8-427a-93ca-a1f532330921">

実際にブラウザで正しく表示されない。本当にヘッダーの隙間に改行が入っているようだ

Cookieを使うCGIの元コードはここ
https://www.tohoho-web.com/wwwcook4.htm

**Comment by Hurumy** [comment]
<img width="1111" alt="スクリーンショット 2023-11-14 17 36 03" src="https://github.com/Hurumy/webserv/assets/61591984/4a2f4baa-9287-425e-b507-03d9c5eb15ad">
ブラウザの表示はこんな感じ

**Comment by ShotaTanemura** [comment]
@Hurumy 僕が開発しているものだと、添付画像のように正常に表示できます (Firefox を使用)。ただ、cookie をCGI スクリプトへ渡す機能を追加していないので、 cookie の有無による描画の変化はまだみれていません。ですので、この issue は、現在の develope ブランチをレビューする際に問題がないか (改行文字の有無など) 確認できた場合は閉じていただけると幸いです。

<img width="1876" alt="スクリーンショット 2023-11-14 19 20 23" src="https://github.com/Hurumy/webserv/assets/70319686/4c9fd8f2-344e-4753-953d-e5ff711daafb">
