### ISSUE TITLE
Directory listing error

### ISSUE THREAD

**Issue by ShotaTanemura** [Hurumy/webserv#123]
- config ファイル内にて、 `root /content;` としており、かつ`content` 下に別のディレクトリ (以下、`subdir/` とする) が存在する場合に、 `localhost:8080/subdir/` というリクエストを送ると正常にディレクトリリスティングが成功するが、 `localhost:8080/subdir` というリクエストを送ると、ディレクトリリスティングが失敗する。
- 以下に示した部分にて、 `MakeDirlistHTML::returnHTML()` にて `path` の後ろに無条件でそのまま `st->d_name` を付け足しているが、`localhost:8080/subdir` といったリクエストを送った場合、`tmpfilepath` が `subdir..` となってしまう。このことを避けるには、`path` の末尾が `/` 出なかった場合には、 `/` を追加するなどすれば解決できるのではないかと考えている。

https://github.com/Hurumy/webserv/blob/02fc85a0872f5c1db9a4331fe15c28e19c45a93f/src/MakeDirlistHTML.cpp#L65

**Comment by Hurumy** [comment]
URI末尾の`/`はtrailing slashといってURIが指すものがディレクトリなのかファイルなのかを示す割と明確な意味がある(POSTとかだとわかりやすい。Trailing slashがないとディレクトリ判定にならなくて失敗する)。

RFCをぐるぐる探した結果、
[RFC1630](https://datatracker.ietf.org/doc/html/rfc1630) 

> "Trailing slashがある場合とない場合のURIは別の扱いを受ける"

[RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.3:~:text=normalizations%20are%20possible.-,6.2.4,-.%20%20Protocol%2DBased%20Normalization) 

> "Trailing slashの有る無しのURIも、利便性のために根気強くリダイレクトするように実装していたらそのうち同一のものとみなされるようになるだろう"

(？何を言っているのかいまいちよくわからない)

的な感じでした。

ただ、NGINXだと該当するファイルを探して、なかった場合はトレイリングスラッシュをつけて再検索するということをある程度やってくれているっぽい。
もっともそんな義務はない。今の実装だとstat()でディレクトリかどうかを確認してからファイルをGETしに行っているので、処理順序まで揃えようとすると、今の実装とフローがまるっきり逆になってしまい修正事項がめちゃくちゃ膨らんでしまう。
とはいえやらないと不便でもある。ユーザーがConfigでRewrite使ってHTTPリダイレクトでやれよ、というのもあり得る。

が、もちろんstat()はパスの字面でディレクトリかファイルか確認しているわけではないので、これが一番信頼できる。

というわけで、stat()でURIの指すもの(Trailing slashがあれば、それを外したもの)がディレクトリであると判定された場合で、しかもTrailing slashがURIにもともとついていなかった場合、リダイレクトで一旦打ち返すか、あるいは勝手にTrailing slashつけて再検索するか、というところで迷っていますが、とりあえずつけて再検索する方で実装してみました。
