### ISSUE TITLE
ディレクトリリスティングがサブディレクトリをリンクに反映してくれていない

### ISSUE THREAD

**Issue by ShotaTanemura** [Hurumy/webserv#152]
**概要**
①の状態から`test.pl`をクリックすると、②のようにパスから`cgi_bin`が抜ける。この問題について確認したのち、パスに抜けがないようにしたい。

①
<img width="881" alt="スクリーンショット 2023-12-26 20 58 14" src="https://github.com/Hurumy/webserv/assets/70319686/80cd3cdc-f9e0-4690-b268-89bf750292bd">

②
<img width="1976" alt="スクリーンショット 2023-12-26 20 58 20" src="https://github.com/Hurumy/webserv/assets/70319686/2bd0bd56-a34b-4e79-9103-ae424be60818">

**Comment by ShotaTanemura** [comment]
@Hurumy こちら担当部分だと思うのでお願いしても良いですか？

**Comment by Hurumy** [comment]
- Configで設定したサーバールートからのパスが見えてしまっているのを、見えないように修正します
- ディレクトリリスティングの際、HTMLに配置するリンクを、すべてルートからの相対URLのものに置き換えます
