### ISSUE TITLE
ft.cppでnamespaceが使われている

### ISSUE THREAD

**Issue by Hurumy** [Hurumy/webserv#181]
Subjectには何も書いていなかったが、一応

**Comment by ShotaTanemura** [comment]
@Hurumy こちらsubjectで使用が禁止されておらず、便利関数を整理することに有効なので使用しています。そのため、このままとしておきたいのですがいかがでしょうか。問題なければcloseしてください。

**Comment by Hurumy** [comment]
了解！ではそうdefenceしましょう。
Scaleにもnamespace禁止とはなかったので。
