### ISSUE TITLE
WS08: Add numerous tests and apply tests

### ISSUE THREAD

**Issue by ShotaTanemura** [Hurumy/webserv#91]
**概要**
本イシューでは、これまでに開発してきた実装部分におけるエラーハンドリング・コーナーケースの不足や左記に対するテストの追加を求める。

**テスト**
python unittest を用いた E2E テストと、 Google test を用いた単体テストの追加を行う。

**単体テスト**
~- [ ] `Metavariables`~ #125 へ移動
~- [ ] `CGIResponseCreator`~ #125 へ移動

**E2E テスト**
- [x] 無限 CGI Local Redirect
- [x] CGI スクリプトが異常終了
- [x] CGI スクリプトがタイムアウト
- [x] CGI レスポンスが不適切
  - [x] CGI レスポンスが空
  - [x] 先頭のヘッダーが `Content-Type` ヘッダーでも `Location` ヘッダーでもない
  - [x] ヘッダーの出力に `:` が存在しない
- [x] バイナリデータの受信
- [x] CGI レスポンスヘッダーの case insensitive 対応
  - [x] `Location`
  - [x] `Content-Type`
- [x] `signal(SIGPIPE, SIGIGN)`

**コーナーケース**
~- [ ] CGI 出力を一回で読みきれない~
- [x] CGI 入力内容が pipe バッファーの上限を超えている
- [x] linux において クライアントソケットの切断を確認するための poll() のオプション
- [x] CGI レスポンス case insensitive 対応

**エラーハンドリング**
- [x] 無限 CGI Local Redirect
- [x] CGI スクリプトが異常終了
  - [x] WIFEXIT, WEXITSTATUS, について調べる
- [x] CGI スクリプトがタイムアウト
- [x] CGI スクリプトが標準出力への書き込みを行なっていない
- [x] CGI スクリプトの位置へ `chidr()`
- [x] `CGIResponseCreator` における `setEnvVars` 内の危険なデータの扱い方について
- [x] `CGI` の非同期安全

~- [ ]~ #115 へ移動
~- [ ]~ #116 へ移動
~- [ ]~ #117 へ移動

**追加機能**
~- [ ] `Request` インスタンスの `header` メンバーに値を追加する際に `key` を全て小文字化してからセットする~
~- [ ] `loadHeader` にて上記を反映する~
~- [ ] `getHeader` にて上記を反映する~
- [x] `RequestHandler` に `Request` と `Response` をリファレンスで持たせても大丈夫？
  - オブジェクトが削除されない、オブジェクトと対応する `key` が存在している保証があるなら問題ないか
- scheme を 'http', 'https' に限定する
**その他**
- [x] `setCGIOutput` のリファクタリング
- [x] `signal(SIGPIPE, SIGIGN)`

**Comment by Hurumy** [comment]
- cgiの実行中に、クライアントが接続を切ってしまうと、その後しばらくブロッキングしてました

**Comment by ShotaTanemura** [comment]
- `REMOTE_ADDR` の値が反転している

**Comment by ShotaTanemura** [comment]
- `SocketHandker` の `csockets` を `std::list` にする。

**Comment by ShotaTanemura** [comment]
- 接続が確立した状態で、 server 側が積極的に接続を切断した場合に、使用していたポートが `TIME_WAIT` 状態へ遷移することを避ける

**Comment by ShotaTanemura** [comment]
> * 接続が確立した状態で、 server 側が積極的に接続を切断した場合に、使用していたポートが `TIME_WAIT` 状態へ遷移することを避ける

done

**Comment by ShotaTanemura** [comment]
> * `REMOTE_ADDR` の値が反転している

done

**Comment by ShotaTanemura** [comment]
- [ ] CGI へ渡す環境変数の値に `:` と ` ` が含まれてしまっている。

**Comment by ShotaTanemura** [comment]
- [ ] `cgiPath` が標準出力されている

**Comment by ShotaTanemura** [comment]
- [ ] `RequestHandler` に渡す前に不適切なリクエストを検知した場合に、 `status: 400`, `status message` の設定

**Comment by ShotaTanemura** [comment]
- [ ] CGI はレスポンスの全体を返してくることを踏まえて実装できていない
