### ISSUE TITLE
画像等、様々なファイルの送受信ができるようにする

### ISSUE THREAD

**Issue by Hurumy** [Hurumy/webserv#95]
- [x] 何故かわからないが、バイナリファイルを取得しようとした時に通信が終わらない。
- [x] 何故か送信が途中で終わっている。53KBあるファイルを要求して14KBしか帰ってきていない。Readで読んでるせいかも

**Comment by ShotaTanemura** [comment]
- [ ] `Content-Length` の値を `std::string::size()` を使うのではなく、`std::strlen()` を使って設定する。
- [ ] 文字列の内容が元のファイルと異なっている。どこかで変換が起きていないか確認する。
